SELECT GENDER,SUM(SALARY) AS TOTAL_SALARY
FROM Employee_Payroll
GROUP BY GENDER;

SELECT GENDER,AVG(SALARY) AS AVERAGE_SALARY
FROM Employee_Payroll
GROUP BY GENDER;

SELECT GENDER,MAX(SALARY) AS MAXIMUM_SALARY
FROM Employee_Payroll
GROUP BY GENDER;

SELECT GENDER,MIN(SALARY) AS MINIMUM_SALARY
FROM Employee_Payroll
GROUP BY GENDER;

SELECT GENDER,COUNT(GENDER) AS TOTAL_COUNT
FROM Employee_Payroll
GROUP BY GENDER;